### ISSUE TITLE
Icon Vertical Centering

### ISSUE THREAD

**Issue by RieMars** [aykutkardas/vue-icomoon#15]
I've got an issue where icons that aren't so square are aligned to the top of their SVG container. Is there a setting or work around for this?

Tried a lot from CSS flex and it's alignment settings to SVG attributes like preserveAspectRatio to get the path centered within the SVG container

**Comment by aykutkardas** [comment]
It is a design flaw that the icons are not square.

In addition, icons must have equal dimensions and safe paddings.

To solve this problem, you can try to improve your icons.

**Comment by RieMars** [comment]
So is there any timeline on fixing the design flaw in svgps that uses only one dimension so size icons?

**Comment by RieMars** [comment]
For those who actually want a clearer solution to this:

You can make your icon linework any ratio or dimension you like. The icon itself could be wide or tall.

The issue is that the SVG must have a square viewbox around the SVG's contents (linework). If you export an icon from Figma, don't just export the linework, make sure it's in a square frame first.

If you're a developer, you can't do anything to fix this in code, well other than modifying SVGPS and vue-icomoon so that it stores the height/width ratio of the linework and a padding value to pass that to vue-icomoon so you can center all the icons with a set padding. This would also allow you to tune each icon's padding individually so you could also resolve the other problem with different amounts of space around icons from different sets, this usually means they look like they're inconsistent sizes on the final site.

But the easier solution is just downloading the offending icon's SVG from SVGPS, using Figma to put a square frame around it, adjusting the negative space and exporting the frame as an SVG and replacing your original in SVGPS.
