### ISSUE TITLE
It seems is not compliant with current file format from icomoon app

### ISSUE THREAD

**Issue by clabnet** [aykutkardas/vue-icomoon#17]
Hi,

Your file has "icon" attribute belong to indexed element :
![image](https://user-images.githubusercontent.com/6067610/218320868-0df7ff46-c8ec-48a4-8269-186d683ff499.png)

I have download **icomoon free** set icons from https://icomoon.io/#icons-icomoon
This file _is missing the **icon** attribute_
![image](https://user-images.githubusercontent.com/6067610/218320947-0b77b10f-c7e9-490a-a8ae-b6b1a954824a.png)

The result is an error using icomoon set icons.

You can try this [codesandbox ](https://codesandbox.io/s/vue-icomoon-demo-forked-j60fy8?file=/src/components/Icon/Icon.vue), forked from [your demo](https://codesandbox.io/s/vue-icomoon-demo-nqb0z)

**Comment by aykutkardas** [comment]
In Icomoon, you need to convert icons to fonts to get the right file. You will see the selection.json file among the files of the icon that has turned into a font.
![image](https://user-images.githubusercontent.com/7966133/218323399-da5cf8d4-2496-4882-8870-51112b92f7ed.png)


But there is an easier way to use these icons. 👇🏻 
https://svgps.app/store/icomoon-free/

![image](https://user-images.githubusercontent.com/7966133/218323425-b6f73fa4-104c-482d-a98a-464ab22400f5.png)

**Comment by clabnet** [comment]
It work using https://svgps.app/store/icomoon-free/
Thank's
