### ISSUE TITLE
Property "title" was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by ctadlock** [aykutkardas/vue-icomoon#3]
Not sure how to resolve this warning. O copied the example exactly except for using my own icomoon `selection.json`.

![image](https://user-images.githubusercontent.com/1539397/140685990-1e8e8945-4c94-4975-bccf-d11ae213641a.png)

PS, this project is great! Exactly what we needed.

**Comment by aykutkardas** [comment]
This is a Vue port of the [react-icomoon](https://github.com/aykutkardas/react-icomoon) project and is still in its early stages. I will fix this as soon as possible.

I'm glad you liked it. Thanks for your feedback.

**Comment by aykutkardas** [comment]
Please check v0.2.1 version. @ctadlock

**Comment by aykutkardas** [comment]
Fixed with v0.2.3 version. @ctadlock

**Comment by ctadlock** [comment]
Fixed; thank you

**Comment by ctadlock** [comment]
Looks great...

![image](https://user-images.githubusercontent.com/1539397/141699352-572d34a6-dc1c-4754-90e5-a02f5e9aa0b9.png)
