### ISSUE TITLE
Trouble with size prop as string

### ISSUE THREAD

**Issue by dan-bowen** [aykutkardas/vue-icomoon#9]
Hello. First, thank you for this library. It saved me a lot of time already.

I wanted to mention an error when trying to send a string for the `size` prop.

If I call the Icon like this:

```html
<Icon name="camera" size="20px" />
```

I get the following Vue warning.

```
[Vue warn]: Invalid prop: type check failed for prop "size". Expected Number with value NaN, got String with value "20px".
```

The README says this can be a Number or String but I think I tracked down the error here:

https://github.com/aykutkardas/vue-icomoon/blob/4328f81c5ba1a41244e4521c92b98a11310e9ea7/src/components/Icomoon.vue#L32-L35

Should the type be like this in order to support strings?
```
type: [String, Number]
```

Thanks in advance for looking at this.

**Comment by aykutkardas** [comment]
Thank you for this report. Fixed. Try `version 0.3.2`
